# Dependencies
markdown:         redcarpet
highlighter:      pygments



# Setup
title:            Gaurish Katlana
tagline:          ''
description:      'A CS student living in San Francisco, travelling around the world '
url:              http://katlana.com
baseurl:          /

author:
  name:           'Gaurish Katlana'
  url:            https://twitter.com/gkatlana

paginate:         3


github:
  repo:           https://github.com/BeyondInfinities
