# Dependencies
markdown:         redcarpet
highlighter:      pygments



# Setup
title:            Gaurish Katlana
tagline:          'A CS student living in San Francisco '
description:      ''
url:              http://katlana.com
baseurl:          /

author:
  name:           'Gaurish Katlana'
  url:            https://twitter.com/gkatlana

paginate:         5


github:
  repo:           https://github.com/BeyondInfinities
